services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2.1
    container_name: aspire-dashboard
    environment:
      Dashboard__Frontend__AuthMode: Unsecured
      DASHBOARD__OTLP__AUTHMODE: ApiKey
      DASHBOARD__OTLP__PRIMARYAPIKEY: 18219ff089b2ca6a7249f8f54d0661c6
    ports:
      - 18888:18888
      - 18889:18889
      - 18890:18890
    networks:
      - otel-net
      
networks:
  otel-net:
    name: "otel-net"
    driver: bridge
    