receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000

exporters:
  elasticsearch:
    logs:
      endpoints: ["https://opensearch-node1:9200"]
      user: "admin"
      password: "Quintry@1234!" # Пароль из docker-compose.yml
      tls:
        insecure: true


service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]